// Generated by scripts/generate-pattern-data.mjs from public/images/backgrounds. Do not hand-edit.

export const IMAGE_BACKGROUNDS: string[] = ["a1","a2","a3","a4","a5","a6","a7","a8","a9","a10","a11","a12","a13","a14","a15","a16","a17","bk0","bk1","bk2","bk3","bk4","bk5","bk6","bk7","bk8","bk9","bk10","bk11","bk12","bk13","bk14","bk15","bk16","bk18","bk19","bk20","bk21","bk22","bk24","bk25","bk26","bk27","bk28","bk31","bk32","bk33","bk34","bk35","bk36","bk37","bk38","bk39","bk40","bk42","bk43","bk44","bk48","bk52","bk54"];
